### PR TITLE
Update factory_reset filename and add folders to compile_protos.sh

### PR DESCRIPTION
**Pull request by samribeiro**

### CODE REVIEW

**Comment by samribeiro** [comment]
#33

**Comment by schandrashek** [comment]
Is there any plan to merge this into master anytime soon?

**Review by robshakir — APPROVED** [review]
Thanks Sam.

**Comment by marcushines** [comment]
can we get these conflicts resolved so we can merge this?

**Comment by hellt** [comment]
this one looks stale? the factory_reset.proto has been renamed in the meanwhile

**Pull request closed without merging**
