### PR TITLE
Remove interface service based on no implementations nor no clear use

### PR DESCRIPTION
**Pull request by marcushines**
gNMI can set all of these configurations at this point This service no longer is needed
Also the reset counters actually breaks many streaming implementations

### CODE REVIEW

**Review by tomek-US — APPROVED** [review]
LGTM

**Comment by dplore** [comment]
Added to agenda for April 18 openconfig operators meeting

**Comment by dplore** [comment]
Reviewed without objection from the OC Operators meeting

**Review by dplore — APPROVED** [review]

**Comment by charanjith-anet** [comment]
Hi,

"gNMI can set all of these configurations at this point"
Can you please give an example of a path+value that can (or is expected to) reset L2 interface counters?

Thanks

**Comment by dplore** [comment]
Hi @charanjith-anet , this PR assumed that reset interface counters is not a needed feature and in fact can break some streaming implementations.  Resetting a counter is viewed as an interactive CLI feature and not a backend telemetry streaming interface.

**Pull request merged**
